name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP 8.2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Validate Composer
        run: composer validate --strict

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Pint
        run: composer format:test

      - name: Run PHPStan
        run: composer analyse

      - name: Run Pest
        run: composer test

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build
